### ISSUE TITLE
Error when parsing the TCC raw files

### ISSUE THREAD

**Issue by yangyushi** [yangyushi/hsmc#2]
```
Traceback (most recent call last):                                         
  File "analyse.py", line 132, in <module>
    count = tcc.clusters[cn][f].ravel().astype(int)
  File "/home/yy17363/Dropbox/Ivan/Wet/lib/hsmc/analysis.py", line 83, in __getitem__
    self.__f, nrows=self.particle_numbers[i], **self.__kwargs
  File "/home/yy17363/.local/lib/python3.7/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/yy17363/.local/lib/python3.7/site-packages/pandas/io/parsers.py", line 454, in _read
    data = parser.read(nrows)
  File "/home/yy17363/.local/lib/python3.7/site-packages/pandas/io/parsers.py", line 1133, in read
    ret = self._engine.read(nrows)
  File "/home/yy17363/.local/lib/python3.7/site-packages/pandas/io/parsers.py", line 2037, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 859, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 886, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 928, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 915, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2070, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 935, saw 2
```

**Comment by yangyushi** [comment]
The TCC wrapper is removed, use [pyTCC](https://github.com/yangyushi/pyTCC) instead.
